import Navbar from "@/components/navbar";
import "./globals.css";
import Head from "next/head";

export const metadata = {
  title: "Mukhtar Ahmad",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <link rel="shortcut icon" href="favicon/favicon.ico" />
      </Head>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
